name: Docker Image CI

on:
  push:
    branches: [ "dev"]
  pull_request:
    branches: [ "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Github checkout
      uses: actions/checkout@v3
    - name: docker_login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker_build
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mynginx:latest .
    - name: Docker_push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mynginx:latest

    - name: SSH into EC2 Instance and Pull Docker Image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_INSTANCE_IP}}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker stop nginx-container
          sudo docker rm nginx-container
          sudo docker run -d -p 80:80 --restart unless-stopped --name nginx-container ${{ secrets.DOCKER_USERNAME }}/mynginx:latest

